# Generated by Django 5.1 on 2024-08-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('College', models.CharField(max_length=100)),
            ],
        ),
    ]
